### ISSUE TITLE
Inferring list as dictionary

### ISSUE THREAD

**Issue by samaspin** [scottmuc/PowerYaml#11]
Hi Scott, thanks for the library.

I noticed when my yaml contains a list with a single item it is being interpreted as the contained items type rather than a list with a single item.  Hopefully the following code will explain a little better!

```
$String1 = "dictitem:
  - Name: Sam
  - Name: Scott"

$String2 = "dictitem:
  - Name: Sam"

(Get-Yaml -FromString $String1)['dictitem'].gettype() # -> Object[] - good
(Get-Yaml -FromString $String2)['dictitem'].gettype() # -> Hashtable - bad
```

I am using this as a configuration file and having only one option in the list should be possible, obviously if I'm expecting an array but get a hashtable instead it's going to cause problems!

I'm guessing this is something to do with the way Powershell interprets single-item lists as I've seen this behaviour before when not using yaml.  Do you think this is something PowerYaml should handle? If so, I'd be happy to have a look around the code and see if I can make it happen.

Sam : )

**Comment by scottmuc** [comment]
Closing due to project retirement.
