### ISSUE TITLE
Converting methods fail in PowerShell 3.0

### ISSUE THREAD

**Issue by scottmuc** [scottmuc/PowerYaml#7]
Add-Member : Cannot add a member with the name "ToDouble" because a member with that name already exists. If you want to overwrite the member anyway, use the Force
parameter to overwrite it.
At C:\Users\brian.ogletree\Desktop\PowerYaml-master\Functions\Casting.ps1:8 char:12
-            Add-Member -Name ToDouble `
-            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (.\sample.yml:PSObject) [Add-Member], InvalidOperationException
  - FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand

**Comment by ryangribble** [comment]
What ever happened to version 1.04?  Is this module no longer supported?  Any other solutions for YAML in powershell?

**Comment by scottmuc** [comment]
@ryangribble ugh, I don't have a Windows machine anymore and this project is sort of abandoned. I haven't done any Windows work since 2011. I would love to help out, but I simply cannot at this point in time. I do intend to get a Windows machine this year (I still like to play games). If that happens I may take a look.

**Comment by scottmuc** [comment]
Closing due to project retirement.
